//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQ_Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Cause { get; set; }
        public string Resolution { get; set; }
    }
}
