//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQ_Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class window
    {
        public int id { get; set; }
        public string winver { get; set; }
        public string topic { get; set; }
        public string question1 { get; set; }
        public string question2 { get; set; }
        public string answer { get; set; }
    }
}
