/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from 'ionic-angular/components/menu/menu';
import * as import13 from 'ionic-angular/components/toolbar/toolbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from 'ionic-angular/components/list/list';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '../components/login/login';
import * as import19 from 'ionic-angular/components/nav/nav';
import * as import20 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import21 from 'ionic-angular/components/menu/menu-controller';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from 'ionic-angular/util/keyboard';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from 'ionic-angular/gestures/gesture-controller';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import29 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import30 from 'ionic-angular/components/navbar/navbar';
import * as import31 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from '../components/login/login.ngfactory';
import * as import37 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import38 from 'ionic-angular/navigation/nav-controller-base';
import * as import39 from '@angular/core/src/linker/component_factory_resolver';
import * as import40 from 'ionic-angular/transitions/transition-controller';
import * as import41 from 'ionic-angular/navigation/deep-linker';
import * as import42 from 'ionic-angular/components/item/item';
import * as import43 from 'ionic-angular/components/menu/menu-close';
import * as import44 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import45 from 'ionic-angular/util/form';
var renderType_MyApp_Host:import0.RenderComponentType = (null as any);
class _View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _MyApp_0_4:import3.MyApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp_Host0,renderType_MyApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyApp_0_4 = new import3.MyApp(this.parentInjector.get(import8.Platform));
    this._appEl_0.initComponent(this._MyApp_0_4,[],compView_0);
    compView_0.create(this._MyApp_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_4; }
    return notFoundResult;
  }
}
function viewFactory_MyApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_MyApp_Host === (null as any))) { (renderType_MyApp_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_MyApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAppNgFactory:import10.ComponentFactory<import3.MyApp> = new import10.ComponentFactory<import3.MyApp>('ng-component',viewFactory_MyApp_Host0,import3.MyApp);
const styles_MyApp:any[] = [];
var renderType_MyApp:import0.RenderComponentType = (null as any);
class _View_MyApp0 extends import1.AppView<import3.MyApp> {
  _viewQuery_Nav_0:import11.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Menu_0_4:import12.Menu;
  _text_1:any;
  _el_2:any;
  _Header_2_3:import13.Header;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Toolbar_4_4:import13.Toolbar;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _ToolbarTitle_6_4:import14.ToolbarTitle;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _Content_11_4:import15.Content;
  _text_12:any;
  _el_13:any;
  _List_13_3:import16.List;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgFor_15_6:import17.NgFor;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _Login_17_4:import18.Login;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _Nav_23_4:import19.Nav;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp0,renderType_MyApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import12.Menu(this.parentInjector.get(import21.MenuController),new import22.ElementRef(this._el_0),this.parentInjector.get(import23.Config),this.parentInjector.get(import8.Platform),this.renderer,this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import26.GestureController));
    this._appEl_0.initComponent(this._Menu_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_2_3 = new import13.Header(this.parentInjector.get(import23.Config),new import22.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','toolbar');
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import28.viewFactory_Toolbar0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Toolbar_4_4 = new import13.Toolbar(this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import23.Config),new import22.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Toolbar_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    var compView_6:any = import29.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(6),this._appEl_6);
    this._ToolbarTitle_6_4 = new import14.ToolbarTitle(this.parentInjector.get(import23.Config),new import22.ElementRef(this._el_6),this.renderer,this._Toolbar_4_4,this.parentInjector.get(import30.Navbar,(null as any)));
    this._appEl_6.initComponent(this._ToolbarTitle_6_4,[],compView_6);
    this._text_7 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_6.create(this._ToolbarTitle_6_4,[[].concat([this._text_7])],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_4.create(this._Toolbar_4_4,[
      [],
      [],
      [],
      [].concat([
        this._text_5,
        this._el_6,
        this._text_8
      ]
      )
    ]
    ,(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n  ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this._appEl_11 = new import2.AppElement(11,0,this,this._el_11);
    var compView_11:any = import31.viewFactory_Content0(this.viewUtils,this.injector(11),this._appEl_11);
    this._Content_11_4 = new import15.Content(this.parentInjector.get(import23.Config),new import22.ElementRef(this._el_11),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_11.initComponent(this._Content_11_4,[],compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_13_3 = new import16.List(this.parentInjector.get(import23.Config),new import22.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import26.GestureController));
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._appEl_15 = new import2.AppElement(15,13,this,this._anchor_15);
    this._TemplateRef_15_5 = new import34.TemplateRef_(this._appEl_15,viewFactory_MyApp1);
    this._NgFor_15_6 = new import17.NgFor(this._appEl_15.vcRef,this._TemplateRef_15_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_16 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_13,'login',(null as any));
    this._appEl_17 = new import2.AppElement(17,13,this,this._el_17);
    var compView_17:any = import36.viewFactory_Login0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Login_17_4 = new import18.Login();
    this._appEl_17.initComponent(this._Login_17_4,[],compView_17);
    compView_17.create(this._Login_17_4,[],(null as any));
    this._text_18 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_11.create(this._Content_11_4,[
      [],
      [].concat([
        this._text_12,
        this._el_13,
        this._text_19
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n\n',(null as any));
      compView_0.create(this._Menu_0_4,[[].concat([
        this._text_1,
        this._el_2,
        this._text_10,
        this._el_11,
        this._text_20
      ]
    )],(null as any));
    this._text_21 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_23 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_23,'swipeBackEnabled','false');
    this._appEl_23 = new import2.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import37.viewFactory_Nav0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Nav_23_4 = new import19.Nav(this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import38.NavControllerBase,(null as any)),this.parentInjector.get(import32.App),this.parentInjector.get(import23.Config),this.parentInjector.get(import24.Keyboard),new import22.ElementRef(this._el_23),this.parentInjector.get(import25.NgZone),this.renderer,this.parentInjector.get(import39.ComponentFactoryResolver),this.parentInjector.get(import26.GestureController),this.parentInjector.get(import40.TransitionController),this.parentInjector.get(import41.DeepLinker,(null as any)));
    this._appEl_23.initComponent(this._Nav_23_4,[],compView_23);
    compView_23.create(this._Nav_23_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_23_4]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ToolbarTitle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarTitle_6_4; }
    if (((token === import13.Toolbar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Toolbar_4_4; }
    if (((token === import13.Header) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Header_2_3; }
    if (((token === import34.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import17.NgFor) && (15 === requestNodeIndex))) { return this._NgFor_15_6; }
    if (((token === import18.Login) && (17 === requestNodeIndex))) { return this._Login_17_4; }
    if (((token === import16.List) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._List_13_3; }
    if (((token === import15.Content) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Content_11_4; }
    if (((token === import12.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Menu_0_4; }
    if (((token === import19.Nav) && (23 === requestNodeIndex))) { return this._Nav_23_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changed = false;
    const currVal_0:any = this._Nav_23_4;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Menu_0_4.content = currVal_0;
      changed = true;
      this._expr_0 = currVal_0;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Menu_0_4.ngOnInit(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_11_4.ngOnInit(); }
    changes = (null as any);
    const currVal_3:any = this.context.pages;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgFor_15_6.ngForOf = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgFor_15_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_15_6.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Login_17_4.ngOnInit(); }
    const currVal_4:any = this.context.rootPage;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Nav_23_4.root = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'false';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Nav_23_4.swipeBackEnabled = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Toolbar_4_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_4,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_11_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_11,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_23_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_11_4.ngOnDestroy();
    this._Menu_0_4.ngOnDestroy();
  }
}
export function viewFactory_MyApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.MyApp> {
  if ((renderType_MyApp === (null as any))) { (renderType_MyApp = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_MyApp,{})); }
  return new _View_MyApp0(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Item_0_4:import42.Item;
  _ItemContent_0_5:import42.ItemContent;
  _MenuClose_0_6:import43.MenuClose;
  _query_Label_0_0:import11.QueryList<any>;
  _query_Button_0_1:import11.QueryList<any>;
  _query_Icon_0_2:import11.QueryList<any>;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_MyApp1,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import44.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import42.Item(this.parent.parentInjector.get(import45.Form),this.parent.parentInjector.get(import23.Config),new import22.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import42.ItemContent();
    this._MenuClose_0_6 = new import43.MenuClose(this.parent.parentInjector.get(import21.MenuController));
    this._query_Label_0_0 = new import11.QueryList<any>();
    this._query_Button_0_1 = new import11.QueryList<any>();
    this._query_Icon_0_2 = new import11.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset([]);
    this._Item_0_4.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4,[
      [],
      [],
      [].concat([this._text_1]),
      [],
      []
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Item_0_4; }
    if (((token === import42.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ItemContent_0_5; }
    if (((token === import43.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._MenuClose_0_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._MenuClose_0_6.menuClose = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset([]);
        this._Item_0_4._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([]);
        this._Item_0_4._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.ngAfterContentInit(); }
    }
    const currVal_3:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_MyApp1(viewUtils,parentInjector,declarationEl);
}