/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './login';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from 'ionic-angular/components/button/button';
import * as import11 from '@angular/common/src/directives/ng_if';
import * as import12 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import13 from 'ionic-angular/config/config';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from 'ionic-angular/components/list/list';
import * as import17 from 'ionic-angular/components/item/item';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from 'ionic-angular/components/avatar/avatar';
import * as import20 from 'ionic-angular/gestures/gesture-controller';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from 'ionic-angular/util/form';
import * as import23 from '@angular/core/src/security';
var renderType_Login_Host:import0.RenderComponentType = (null as any);
class _View_Login_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _Login_0_4:import3.Login;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Login_Host0,renderType_Login_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('login',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Login0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Login_0_4 = new import3.Login();
    this._appEl_0.initComponent(this._Login_0_4,[],compView_0);
    compView_0.create(this._Login_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.Login) && (0 === requestNodeIndex))) { return this._Login_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Login_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Login_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_Login_Host === (null as any))) { (renderType_Login_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_Login_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginNgFactory:import9.ComponentFactory<import3.Login> = new import9.ComponentFactory<import3.Login>('login',viewFactory_Login_Host0,import3.Login);
const styles_Login:any[] = [];
var renderType_Login:import0.RenderComponentType = (null as any);
class _View_Login0 extends import1.AppView<import3.Login> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _Button_1_4:import10.Button;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _Button_4_4:import10.Button;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _Button_7_4:import10.Button;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _Button_10_4:import10.Button;
  _text_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import11.NgIf;
  _text_14:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Login0,renderType_Login,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_1,'ion-button','');
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import12.viewFactory_Button0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Button_1_4 = new import10.Button((null as any),'',this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_1),this.renderer);
    this._appEl_1.initComponent(this._Button_1_4,[],compView_1);
    this._text_2 = this.renderer.createText((null as any),'Login',(null as any));
    compView_1.create(this._Button_1_4,[[].concat([this._text_2])],(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this._appEl_4 = new import2.AppElement(4,(null as any),this,this._el_4);
    var compView_4:any = import12.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import10.Button((null as any),'',this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_4),this.renderer);
    this._appEl_4.initComponent(this._Button_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'Login Silent',(null as any));
    compView_4.create(this._Button_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_7,'ion-button','');
    this._appEl_7 = new import2.AppElement(7,(null as any),this,this._el_7);
    var compView_7:any = import12.viewFactory_Button0(this.viewUtils,this.injector(7),this._appEl_7);
    this._Button_7_4 = new import10.Button((null as any),'',this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_7),this.renderer);
    this._appEl_7.initComponent(this._Button_7_4,[],compView_7);
    this._text_8 = this.renderer.createText((null as any),'Log Out',(null as any));
    compView_7.create(this._Button_7_4,[[].concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'button',(null as any));
    this.renderer.setElementAttribute(this._el_10,'ion-button','');
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import12.viewFactory_Button0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Button_10_4 = new import10.Button((null as any),'',this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_10),this.renderer);
    this._appEl_10.initComponent(this._Button_10_4,[],compView_10);
    this._text_11 = this.renderer.createText((null as any),'Disconnect',(null as any));
    compView_10.create(this._Button_10_4,[[].concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_13 = new import2.AppElement(13,(null as any),this,this._anchor_13);
    this._TemplateRef_13_5 = new import15.TemplateRef_(this._appEl_13,viewFactory_Login1);
    this._NgIf_13_6 = new import11.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._anchor_13,
      this._text_14
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.Button) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 2)))) { return this._Button_1_4; }
    if (((token === import10.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Button_4_4; }
    if (((token === import10.Button) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_7_4; }
    if (((token === import10.Button) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Button_10_4; }
    if (((token === import15.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import11.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = this.context.profile;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_13_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_1_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_7_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_10_4.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_0);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loginSilent()) !== false);
    return (true && pd_0);
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.disconnect()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Login0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.Login> {
  if ((renderType_Login === (null as any))) { (renderType_Login = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_Login,{})); }
  return new _View_Login0(viewUtils,parentInjector,declarationEl);
}
class _View_Login1 extends import1.AppView<any> {
  _el_0:any;
  _List_0_3:import16.List;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Item_2_4:import17.Item;
  _ItemContent_2_5:import17.ItemContent;
  _query_Label_2_0:import18.QueryList<any>;
  _query_Button_2_1:import18.QueryList<any>;
  _query_Icon_2_2:import18.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Avatar_4_3:import19.Avatar;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_Login1,renderType_Login,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_0_3 = new import16.List(this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import20.GestureController));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import21.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import17.Item(this.parentInjector.get(import22.Form),this.parentInjector.get(import13.Config),new import14.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import17.ItemContent();
    this._query_Label_2_0 = new import18.QueryList<any>();
    this._query_Button_2_1 = new import18.QueryList<any>();
    this._query_Icon_2_2 = new import18.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Avatar_4_3 = new import19.Avatar();
    this._text_5 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._query_Label_2_0.reset([]);
    this._Item_2_4.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4,[
      [].concat([this._el_4]),
      [],
      [].concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      ),
      [],
      []
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.Avatar) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Avatar_4_3; }
    if (((token === import17.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Item_2_4; }
    if (((token === import17.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ItemContent_2_5; }
    if (((token === import16.List) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._List_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([]);
        this._Item_2_4._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset([]);
        this._Item_2_4._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.profile.imageUrl,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.context.profile.displayName,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Login1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_Login1(viewUtils,parentInjector,declarationEl);
}