class PostBack:
  PAY_LOAD_CATEGORY = "Category"
  PAY_LOAD_WORD = "Word"
  PAY_LOAD_QUESTION = "Question"
  PAY_LOAD_DO_EXERCISE = "Exercise"
  PAY_LOAD_MENU_HELP = "MENU_HELP"
  PAY_LOAD_MENU_ACCOUNT = "MENU_ACCOUNT"
  PAY_LOAD_MENU_PROCESS = "MENU_PROCESS"
