/**
 * Created by Thinking on 09/22/2016.
 */

var express = require('express');
var router = express.Router();
var db = require('../utils/mongo1970');
var Collect = require('../utils/collection');
var Category = require('../models/physical/Category');
var Resp = require('../models/logical/Resp');
var Unit = require('../models/physical/Unit');
var random = require('../utils/random');
var Question = require('../models/physical/Question');

router.get('', (req, res) => {
    res.redirect('insert/category');
});

router.get('/category', (req, res) => {
    var category = [];
    category.push(Category.init("Listening", "https://www.socialmediaexplorer.com/wp-content/uploads/2014/03/Listen.jpg"));
    //category.push(Category.init("Speaking", "https://www.speakmoreclearly.com/wp-content/uploads/2016/03/iStock_000012499903Small-trans_543_300_c1.png"));
    category.push(Category.init("Reading", "https://www.timeshighereducation.com/sites/default/files/styles/the_breaking_news_image_style/public/books-open-on-table.jpg?itok=i4wJDL9A"));
    //category.push(Category.init("Writing", "http://www.chf.vu.lt/wp-content/uploads/2016/07/creative-writing.jpg"));
    category.push(Category.init("Grammar", "http://mrbrownslearningspace.com/wp-content/uploads/2014/05/grammar.jpg"));

    db.dropTable(Collect.category);

    db.insertMany(Collect.category, category, (result) => {
        console.log(JSON.stringify(result));
        res.redirect('unit');
    });

});

router.get('/unit', (req, res) => {

    db.dropTable(Collect.unit);

    db.dropTable(Collect.question);

    db.fetchAll(Collect.category, (result) => {
        var categories = result;
        Array.from(categories).forEach((x) => {
            if (x.categoryName === 'Listening') {

            } else if (x.categoryName === 'Speaking') {

            } else if (x.categoryName === 'Reading') {
                var units = [];
                units.push(Unit.init('Yoda - the cat with four ears', 'In Chicago, Illinois, couple Valerie and Ted Rock took the cat in two years ago after...', 'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg', 'In Chicago, Illinois, couple Valerie and Ted Rock took the cat in two years ago after they visited a local bar, where a group of drinkers were handing the animal around and making fun of him. Since being adopted by the Rocks and after getting his picture posted on the Internet, the two-year-old cat immediately became famous. The Rocks have received calls from Good Morning America, Fox News and The Tyra Banks Show. His pictures are shown in many magazines. People are surprised at his extra pair of ears. Despite his strange appearance, Yoda - named after the pointy-eared Star Wars character - is a perfectly normal and attractive cat. His extra ears are thought to be the result of a genetic mutation. He likes being taken for a walk with his owners. But Yoda\'s owners are keeping a close watch on their much-loved pet.', random.int(1000), x._id, Date(), 600000, 'Reading'));
                units.push(Unit.init('Salt coffee – Last Part', 'After 40 years, he passed away, left her a letter which said: “My dearest, please...', 'https://noidung.tienganh123.com/file/baihoc/reading/beginner/bai22/bai22.jpg', 'After 40 years, he passed away, and left her a letter which said: “My dearest, please forgive me, forgive my life\'s lie. This was the only lie I said to you - the salty coffee. Remember the first time we dated?I was so nervous at that time, actually I wanted some sugar, but I said salt, it was hard for me to change so I just went ahead. I never thought that would be the start of my biggest lie. I tried to tell you the truth many times in my life, but I was too afraid to, as I had promised never to lie to you. Now I’m dying, and afraid of nothing so I will tell you the truth: I don’t like salty coffee, what a strange bad taste!But I have had salty coffee for my whole life.Since I have known you, I have never felt sorry for anything I have done for you. Having you with me is the biggest happiness of my life.If I could live again, I would want to know you and have you for my whole life, even if I had to drink the salty coffee again.”Her tears made the letter totally wet. Some day, someone asked her: "How does salty coffee taste?" "It’s sweet," she replied. ', random.int(1000), x._id, Date(), 600000, 'Reading'));
                db.insertMany(Collect.unit, units, (result) => {

                });
            } else if (x.categoryName === 'Writing') {

            } else if (x.categoryName === 'Grammar') {
                var units = [];

                units.push(Unit.init('Unit 01: Danh từ (Nouns)', 'Danh từ trong tiếng anh', 'https://data.tienganh123.com/images/avatar/unit1.jpg', 'Chọn danh từ trong các đáp án', random.int(1000), x._id, Date(), 600000, 'Grammar'));
                units.push(Unit.init('Unit 02: Danh từ đếm được và không đếm được', 'Danh từ đếm được và không đếm được', 'https://data.tienganh123.com/images/avatar/lntacb_unit8.jpg', 'Chọn đáp án thích hợp để điền vào chỗ trống.', random.int(1000), x._id, Date(), 600000, 'Grammar'));
                units.push(Unit.init('Unit 03: Thì hiện tại đơn', 'Trong bài này, chúng ta cùng tìm hiểu về thì hiện tại đơn', 'https://data.tienganh123.com/images/avatar/lntacb_unit10.jpg', 'Chọn đáp án đúng hoàn thành câu', random.int(1000), x._id, Date(), 600000, 'Grammar'));
                units.push(Unit.init('Unit 04: Thì quá khứ đơn', 'Trong bài này, chúng ta cùng tìm hiểu về thì quá khứ đơn', 'http://i.huffpost.com/gen/1119986/images/o-HOW-PHOTOGRAPHS-BOOST-HAPPINESS-facebook.jpg', 'Chọn động từ phù hợp điền vào chỗ trống', random.int(1000), x._id, Date(), 600000, 'Grammar'));

                db.insertMany(Collect.unit, units, (results) => {

                    db.findOne(Collect.unit, {'unitTitle': 'Unit 01: Danh từ (Nouns)'}, (result) => {
                        var questions = [];

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "cat";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "go";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "hot";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "fat";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "balloon";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "pass";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "louldy";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "eat";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "add";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "quietly";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "cake";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "successful";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "abroad";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "beef";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "listen";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "handsome";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "clean";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "kick";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "mouse";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "outside";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "here";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "flag";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "attractively";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "milky";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "bedroom";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "so";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "ugly";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "make";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "never";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "be";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "cold";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "fog";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "D", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "old";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "often";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "happen";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "Henry";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "D", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "dad";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "sit";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "next";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "badSau ";
                        answers.push(answer);
                        questions.push(Question.init("", result._id, "A", answers));
                        db.insertMany(Collect.question, questions, (res) => {});
                    });
                    db.findOne(Collect.unit, {'unitTitle': 'Unit 02: Danh từ đếm được và không đếm được'}, (result) => {
                        var questions = [];

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "soap";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "wine";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "water";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "fat";
                        answers.push(answer);
                        questions.push(Question.init("I need a bar of_____________.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "pizza";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "wine";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "ice cream";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "eat";
                        answers.push(answer);
                        questions.push(Question.init("There’s a bottle of_____________on the table.", result._id, "B", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "beer";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "cake";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "ice";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "sweet";
                        answers.push(answer);
                        questions.push(Question.init("She has a can of_____________.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "water";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "coffee";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "corn";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "handsome";
                        answers.push(answer);
                        questions.push(Question.init("An ear of_____________is over there.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "cheese";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "pizza";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "water";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "bread";
                        answers.push(answer);
                        questions.push(Question.init("He wants to drink a glass of_____________.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "pizza";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "gas";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "water";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "milk";
                        answers.push(answer);
                        questions.push(Question.init("Please give me a slice of_____________.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "corn";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "pizza";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "gas";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "cake";
                        answers.push(answer);
                        questions.push(Question.init("They will bring us a tank of_____________.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "ice";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "milk";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "water";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "fog";
                        answers.push(answer);
                        questions.push(Question.init("Here is a cube of_____________.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "soap";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "toothpaste";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "water";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "Henry";
                        answers.push(answer);
                        questions.push(Question.init("Well, take a tube of_____________for me, please.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "soap";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "toothpaste";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "next";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "bad";
                        answers.push(answer);
                        questions.push(Question.init("There is a keg of_____________in the warehouse.", result._id, "C", answers));

                        db.insertMany(Collect.question, questions, (res) => {});
                    });
                    db.findOne(Collect.unit, {'unitTitle': 'Unit 03: Thì hiện tại đơn'}, (result) => {
                        var questions = [];

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "have";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "has";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "have had";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "had";
                        answers.push(answer);
                        questions.push(Question.init("My teacher (have).................. long hair.", result._id, "B", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "isn't want";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "doesn't want";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "not want";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "don’t want";
                        answers.push(answer);
                        questions.push(Question.init("They (not want )………to play the love games.", result._id, "D", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "Be";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "Are";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "Is";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "isn't";
                        answers.push(answer);
                        questions.push(Question.init(" ............. Marry (be) an English person?", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "doesn't know";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "don’t know";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "isn't knowing";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "aren't knowing";
                        answers.push(answer);
                        questions.push(Question.init("The new comers (not know)…...............…… the rules of the club.", result._id, "B", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "go";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "goes";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "do";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "did";
                        answers.push(answer);
                        questions.push(Question.init("How often does John (go)………… to the library?", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "is living, get";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "lives, get";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "lives, gets";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "is living, gets";
                        answers.push(answer);
                        questions.push(Question.init("Martin (live)………..in a small flat. He and his wife always (get)……….up early to water flowers.", result._id, "B", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "am";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "is";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "are";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "do";
                        answers.push(answer);
                        questions.push(Question.init("I _____ (be) a student.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "don’t speak";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "doesn’t speak";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "not speak";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "is speak";
                        answers.push(answer);
                        questions.push(Question.init("His students ________ (not, speak) German in class.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "isn't";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "not is";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "are not";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "was";
                        answers.push(answer);
                        questions.push(Question.init("She ________ (not, be) six years old.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "working";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "works";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "work";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "worked";
                        answers.push(answer);
                        questions.push(Question.init("John ________ (work) in a supermarket.", result._id, "B", answers));

                        db.insertMany(Collect.question, questions, (res) => {});

                    });
                    db.findOne(Collect.unit, {'unitTitle': 'Unit 04: Thì quá khứ đơn'}, (result) => {
                        var questions = [];

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "was";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "were";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "to be";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "to was";
                        answers.push(answer);
                        questions.push(Question.init("I (be)___ a student in Moloxop School in 1998.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "duck/go";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "ducks/go";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "ducks/went";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "duck/went";
                        answers.push(answer);
                        questions.push(Question.init("A number of (duck) ___ (go) ___ through here, yesterday.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "saw/year";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "seen/weeks";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "see/months";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "saw/months";
                        answers.push(answer);
                        questions.push(Question.init("I last (see)___ her at her house two ____ ago.", result._id, "D", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "won";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "to won";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "A, B, C";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "win";
                        answers.push(answer);
                        questions.push(Question.init("She (win) ___ the gold medal in 1986.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "left";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "leave";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "leaving";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "had left";
                        answers.push(answer);
                        questions.push(Question.init("He had taught in this school before he (leave)____ for London.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "see";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "saw";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "seing";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "seen";
                        answers.push(answer);
                        questions.push(Question.init("I didn't (see)_____ you before.", result._id, "A", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "do/does";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "do/do";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "do/did";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "did/did";
                        answers.push(answer);
                        questions.push(Question.init("What did you (do) ______ last night? - I (do) ______ my homework.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "like";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "liked";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "didn't like";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "didn't liked";
                        answers.push(answer);
                        questions.push(Question.init("He (like)_________ tomatoes before. But, He is eating it now.", result._id, "D", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "studies";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "study";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "studied";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "were study";
                        answers.push(answer);
                        questions.push(Question.init("I (study)__________ French when I was a child.", result._id, "C", answers));

                        var answers = [];
                        var answer = {};
                        answer.ansId = "A";
                        answer.ansContent = "wash";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "B";
                        answer.ansContent = "washing";
                        answers.push(answer);
                        answer = {};
                        answer.ansId = "C";
                        answer.ansContent = "washed";
                        answers.push(answer);
                        var answer = {};
                        answer.ansId = "D";
                        answer.ansContent = "is washing";
                        answers.push(answer);
                        questions.push(Question.init("Mrs. Nhung (wash) the dishes yesterday.", result._id, "A", answers));

                        db.insertMany(Collect.question, questions, (res) => {});
                    });
                });
            }
        });
    });

    res.end();
});

module.exports = router;