//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQ_Bot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class help
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public string question { get; set; }
        public string sub_question { get; set; }
        public string answer { get; set; }
        public string link { get; set; }
    
        public virtual category category { get; set; }
    }
}
